name: Test Build

# NOTE: build logic is duplicated here and in publish.yml

# Run on the master branch commit push and PRs to master (note conditional below)
on:
  push:
    branches:    
      - master
  pull_request:
    branches:
      - master

jobs:
  build_wheels:

    # Only run if the commit message contains '[ci build]'
    if: "contains(toJSON(github.event.commits.*.message), '[ci build]') || contains(toJSON(github.event.pull_request.title), '[ci build]')"

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, macos-15-intel, macos-latest]

    name: Build wheels ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12' 

      - name: Package source distribution
        # make sure this only happens on one of the runners, not repeated on all
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install build
          python -m build --sdist

      - name: Run cibuildwheel
        uses: pypa/cibuildwheel@v3.3.1
        with:
          config-file: ".github/workflows/cibuildwheel_config.toml"

      - name: Copy source distribution into wheelhouse
        if: matrix.os == 'ubuntu-latest'
        run: mv dist/*.tar.gz wheelhouse/

      # Upload binaries to the github artifact store
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: |
            ./wheelhouse/*.whl 
            ./wheelhouse/*.tar.gz
          overwrite: true

      # Upload binaries to the github artifact store
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: |
            ./wheelhouse/*.whl 
            ./wheelhouse/*.tar.gz
          overwrite: true